name: gdm
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0
  - c-ares=1.17.
  - ca-certificates=2020.12
  - certifi=2020.12.
  - cftime=1.3.
  - cmocean=2.0=py_3
  - colorspacious=1.1.2=pyh24bf2e0_0
  - curl=7.71
  - cycler=0.10.0=py_2
  - freetype=2.10.4
  - geos=3.8.1
  - gsw=3.4
  - hdf4=4.2.13
  - hdf5=1.10.6
  - jpeg=9d
  - kiwisolver=1.3.0
  - krb5=1.17
  - lcms2=2.11
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - libcurl=7.71
  - libcxx=11.0.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran
  - libgfortran5=9.3
  - liblapack=3.9.0=3_openblas
  - libnetcdf=4.7.4
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libtiff=4.1.
  - libwebp-base=1.1.
  - llvm-openmp=11.0
  - lz4-c=1.9.2
  - matplotlib=3.3.2
  - matplotlib-base=3.3.
  - ncurses=6.2
  - netcdf4=1.5.4
  - numpy=1.19
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1h
  - pandas=1.0.1
  - pillow=8.0.
  - pip=20.2.4=py_0
  - pyaml=20.4.0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.8.
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.4=pyhd8ed1ab_0
  - pyyaml=5.3.1
  - readline=8.0
  - scipy=1.5.3
  - setuptools=50.3.1
  - shapely=1.7
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.
  - tk
  - tornado=6.1
  - wheel=0.35.1=pyh9f0ad1d_0
  - xarray=0.16.1=py_0
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4
  - pip:
    - astral==2.2
    - glidertools==2020.5
    - joblib==0.17.0
    - numexpr==2.7.1
    - scikit-learn==0.23.2
    - seawater==3.3.4
    - threadpoolctl==2.1.0
    - tqdm==4.54.1

